---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: prod
data:
  initdb.sql: |
    CREATE USER 'root'@'*' IDENTIFIED BY 'root';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'*' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS sehirler;
    use sehirler;
    CREATE TABLE buyuk_sehirler (
        isim VARCHAR(20),
        plaka VARCHAR(10)
    );
    INSERT INTO buyuk_sehirler
        (isim, plaka )
    VALUES
        ('Istanbul', '34'),
        ('Ankara', '06');
