---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydb-pv-volume-test
  namespace: prod
spec:
  capacity:
    storage: 0.3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mydb-prod"
