---
apiVersion: v1
kind: Service
metadata:
  name: mydb
  namespace: test
  labels:
    app: mydb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30338
  selector:
    app: mydb
  type: NodePort
